spring:
  application:
    name: ms-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/antifraud_auth_db
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS

jwt:
  secret: HKyFBQAmRYY+1GF1G+y3WkIKhY/oOVavEVaYe4abJhVU5dqKSU8pvLdyeCfDGj2a
  expiration: 3600000