server:
  port: 8082
spring:
  application:
    name: ms-antifraud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/anti_fraud_db
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    exchange:
      order: order.exchange
    queues:
      orderCreated: order.created.queue
      fraudResult: fraud.result.queue
    routing-keys:
      orderCreated: order.created
      fraudChecked: fraud.checked
